### PR TITLE
feature/Create_Java_Project_#21

### PR DESCRIPTION
**Pull request by galrosenthal**
TG-#213 #done

### CODE REVIEW

**Comment by galrosenthal** [comment]
TG-#213 #closed

**Comment by galrosenthal** [comment]
TG-213 #closed

**Comment by yiftachsa** [comment]
WOW!!! you way overdid that :) :) :)
The overall division and structure looks very well done!
You even started implementing some UCs, that's awesome!

I didn't have time to review any of the implementations of any function yet. 
This review strictly regards the structure of the project. 

Packages:
Game:
the Game package should either focus on game related entities or be renamed.
the problem that I see is with League, Season, Stadium and Team Classes.
It's fine to include all of those classes in a single package, just not under the name "Game".

Logger:
Maybe it's a good name, I mistook it as a log packege. Maybe "GameLogger" would be better.

-----------
Class Diagram:
in the class diagram the Score class should be connetcted to the event log and not to the game.

"Score" class name:
Should be changed to "GameScore" or another a little more descriptive name.

"CoachQualification":
Colud be included in the Coach class for simplicity.

Pages:
All the personal pages should be in a seperate class.

You did a great job!

**Comment by galrosenthal** [comment]
TG-213 #closed

**Pull request merged**
